function ElemPattern = GenerateElementPattern()

ElemPattern = @(polmode,powmode,theta_p,phi_p,zeta)...
    AntennaStructure.ElementPattern.ComputePolarization(...
    polmode, ...
    @AntennaStructure.ElementPattern.ComputePowerPattern,...
    powmode, ...
    theta_p, ...
    phi_p, ...
    zeta);

end